### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Vishal-Parasram**
Adding social media link

### CODE REVIEW

**Comment by Vishal-Parasram** [comment]
@Anupkjha2601 
Review and merge requested.

**Comment by Vishal-Parasram** [comment]
@Anupkjha2601 ready to merge

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by Anupkjha2601** [comment]
merged it .

**Comment by Vishal-Parasram** [comment]
@Anupkjha2601 Add GSSoC-23 label. I work under GSSoC-23.

**Pull request merged**
