### PR TITLE
Revert "added a new logo"

### PR DESCRIPTION
**Pull request by manasi-jain**
Reverts Anupkjha2601/finalproj#10

### CODE REVIEW

**Comment by manasi-jain** [comment]
Hey @Anupkjha2601 facing the issue [Azure Static Web Apps CI/CD / Build and Deploy Job failed].
Is the problem from my end ?

**Comment by Anupkjha2601** [comment]
Hello Mansi,
Why you have closed the pull request.
I am working to correct build and deploy issue. I merged it and I have to
add labels so I am adding labels.

**Comment by manasi-jain** [comment]
Hey @Anupkjha2601 I apologize for the confusion. I accidentally reverted the pull request. When I attempted to resubmit it, I encountered a situation where no changes were detected. This occurred because the code I intended to include had already been merged into the main branch. Consequently, the system indicated that there were no new modifications to incorporate in the pull request.

**Comment by manasi-jain** [comment]
What do i do now ?

**Comment by manasi-jain** [comment]
Hey @Anupkjha2601 
I have raised a new issue #126 
Please do check it out and assign it to me 
I appreciate your attention to this matter and look forward to your response.

**Comment by Anupkjha2601** [comment]
Yes , I will assign it to you, on previous issues I had merged it earlier
it is working so I am  adding labels on it .

**Comment by manasi-jain** [comment]
Thank you for your action on the previous issues. I appreciate your efforts.

**Pull request closed without merging**
