### PR TITLE
Added all the provided links

### PR DESCRIPTION
**Pull request by Ijaiswalshivam**
all links have been added

### CODE REVIEW

**Comment by manasi-jain** [comment]
Hey @Ijaiswalshivam  facing the same merge issue [Azure Static Web Apps CI/CD / Build and Deploy Job failed]. 
Is the problem from our end ?
@Anupkjha2601 do let us know

**Comment by Ijaiswalshivam** [comment]
@manasi-jain it can only be answered by @Anupkjha2601 🥲

**Comment by Ijaiswalshivam** [comment]
@Anupkjha2601 please merge it.

**Comment by Anupkjha2601** [comment]
there is one conflict between 608 to 615 line in index.html file, so check it

**Comment by Ijaiswalshivam** [comment]
conflict is resolved : )

**Review by Anupkjha2601 — APPROVED** [review]

**Comment by Anupkjha2601** [comment]
done brother.

**Comment by Ijaiswalshivam** [comment]
also please mark/label it to GSsoc'23

**Pull request merged**
